### ISSUE TITLE
Add constraints for page creation

### ISSUE THREAD

**Issue by evangelion1204** [qa-tools/qa-tools#121]
To detect that the current page does not match the current displayed website it would be great to add some constraints that are checked when the page is being created and throw an exception if those are not matched.

This will make it easier to write tests because we don't need to assert for the correct page class, which is not possible, because we don't expose the page locator to resolve the page class and do a assertion on the class instance.

A default constraint could be `@page-url`, which we could check for if it is matching. Although many shopping websites use SEO-friendly URLs and for those its not possible to detect the page by checking the URL.

We could introduce a `@constraint` annotation which could contain
* a URL
* an array of possible URLs 
* a RegExp to match against the URL
* a selector (like find-by) to an element which the page should contain - _I use CSS classes and data-attributes for JS to know which code to execute_
* query (GET) parameters of the current URL

**Comment by aik099** [comment]
We can add `opened()` method, that would return true/false to indicate if this page is opened. Then you can have something `$this->assertEquals($this->page->opened())` in test code.

The most problematic case would be e-commerce websites where we can have `product detail page`, but url of that page looks like `/path/to/category/product-title.html`.

> a URL

We can use `WebAssert::addressEquals` method of Mink (see https://github.com/minkphp/Mink/blob/master/src/WebAssert.php#L49) as a start, which used in Behat scenario steps too.

The `cleanUrl` method (see https://github.com/minkphp/Mink/blob/master/src/WebAssert.php#L747) strips everything from compared url except SEO path and anchor. For websites, which pass current page name in query parameters this of course is not accepted solution.

> an array of possible URLs

Doesn't sound right. In product detail page example we'll post list of possible page urls. What if query parameters differ slightly and we already don't have full match.

> a RegExp to match against the URL

That is better, but yet again what about cases, where order of query string parameters is different. How do we compare then.

>  selector (like find-by) to an element which the page should contain - I use CSS classes and data-attributes for JS to know which code to execute

That sounds too website-specific. Having some markers on page to assist it's testing doesn't sound right.

> query (GET) parameters of the current URL

That sounds more like `@page-url` annotation itself where you can define url parts in any order and then we combine them to get final url. This way instead of comparing full url we can compare values of indicated query string parameters of it.

In any case we need to keep in mind 2 urls:
* seo: /language/path/to/template.html
* non-seo: /index.php?language=en&template=/path/to/template

**Comment by aik099** [comment]
Maybe something like `@page-url-match` annotation which is similar to `@page-url` annotation, but in there you can specify regular expression instead of values of `/path/to/template.html` and each query string parameters.
